name: Deploy to AWS Amplify

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16 # Adjust Node.js version as needed
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Ensure this matches your build script in package.json

      - name: Configure Amplify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          npm install -g @aws-amplify/cli
          amplify configure --usage-data-off headless 
          amplify configure headless --accessKeyId $AWS_ACCESS_KEY_ID --secretAccessKey $AWS_SECRET_ACCESS_KEY --region $AWS_REGION
          amplify init --envName main
          amplify push 
          
      - name: Deploy to Amplify
        run: |
          amplify publish --yes

      #- name: Deploy to AWS Amplify
        #run: |
          #curl -X POST \
            #-H "Authorization: Bearer ${{ secrets.AWS_AMPLIFY_ACCESS_TOKEN }}" \
            #"https://amplify.us-east-1.amazonaws.com/apps/${{ secrets.AWS_AMPLIFY_APP_ID }}/branches/main/deployments" 
        
